export const localStorageProperties = {
    Token: "LOCALSTORAGE_TOKEN"
}

export const FETCH_BREEDS_START   = 'FETCH_BREEDS_START';
export const FETCH_BREEDS_SUCCESS = 'FETCH_BREEDS_SUCCESS';
export const FETCH_BREEDS_FAILURE = 'FETCH_BREEDS_FAILURE';

export const FETCH_BREED_START   = 'FETCH_BREED_START';
export const FETCH_BREED_SUCCESS = 'FETCH_BREED_SUCCESS';
export const FETCH_BREED_FAILURE = 'FETCH_BREED_FAILURE';

export const FETCH_SUBBREEDS_START   = 'FETCH_SUBBREEDS_START';
export const FETCH_SUBBREEDS_SUCCESS = 'FETCH_SUBBREEDS_SUCCESS';
export const FETCH_SUBBREEDS_FAILURE = 'FETCH_SUBBREEDS_FAILURE';

export const FETCH_SUBBREED_START   = 'FETCH_SUBBREED_START';
export const FETCH_SUBBREED_SUCCESS = 'FETCH_SUBBREED_SUCCESS';
export const FETCH_SUBBREED_FAILURE = 'FETCH_SUBBREED_FAILURE';
